version: '1.0.0'

services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: test
            POSTGRES_PASSWORD: password
    
    redis:
        image: redis
        ports:
            - "6379:6379"