version: '3.8'

services:
  app:
    image: jaffarabbas/redis-app
    container_name: jaffar-redis
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    networks:
      - darklord
    stdin_open: true  # Equivalent to -i (interactive)
    tty: true         # Equivalent to -t (TTY)

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - darklord

networks:
  darklord:
    driver: bridge
